interface=swlan0
driver=nl80211
ssid=M326B-5G-80M
hw_mode=a
channel=44
ieee80211n=1
ieee80211ac=1
no_pri_sec_switch=1
ht_capab=[HT40+]
vht_oper_chwidth=1
vht_oper_centr_freq_seg0_idx=42
wpa=2
wpa_passphrase=12345678
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
